### ISSUE TITLE
Rename "spectral solver" to EigenPoissonSolver in the code.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#106]
>The core of the method is an eigenfunction expansion of the discrete Poisson operator... I think?
>
>Perhaps we can call this a `EigenPoissonSolver`, or even `FFTPoissonSolver` --- through we should use caution to avoid misleading people into thinking that our code is spectral. This algorithm solves the Poisson equation when it has been *discretized on a staggered grid*. We should not discuss spectral methods or Fourier transforms, and the word 'spectral' should not appear anywhere in the code. I think this is very misleading. It should be a high priority to change this language.
>
>_Originally posted by @glwagner in https://github.com/climate-machine/Oceananigans.jl/issues/102#issuecomment-468947308_

I think `EigenPoissonSolver` is a better name. Just creating a separate issue as this should be a pretty easy item to resolve, and is separate from updating the documentation.

**Comment by glwagner** [comment]
@ali-ramadhan here is my proposed re-factor of the poisson solver:

https://github.com/glwagner/Oceananigans.jl/blob/poisson-solver-refactor/src/poisson_solver.jl

Now may be the right time to move it to a new package, because we can run the tests independent from oceananigans before refactoring oceananigans itself.

**Comment by glwagner** [comment]
Closed by #109
