### ISSUE TITLE
Validation and performance benchmarks.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#136]
We should incorporate the following validation tests which we can also use for performance benchmarking.
- [ ] Free convection (check heat budget, mixed layer depth, and turbulent kinetic energy)
- [ ] Rayleigh–Bénard convection (compare Nusselt and Péclet numbers)
- [x] Deep convection (regression test)
- [x] Rising thermal bubble?
- [ ] Stress-driven flow (not clear which experiment we run)

**Comment by ali-ramadhan** [comment]
Deep convection and rising thermal bubble regression tests (or _golden master_ tests) have been implemented in PR #140.

@SandreOuza Do you have time to work on the Rayleigh–Bénard convection and free convection tests? I think you understand the physics that need to be tested better than anyone.

**Comment by SandreOuza** [comment]
I can work on some of these simulations on Friday

**Comment by ali-ramadhan** [comment]
That'll be awesome, we can work on them together.

**Comment by ali-ramadhan** [comment]
Some ideas for testing free convection:
 - [ ] Check to see if the volume temperature drifts linearly as expected.

**Comment by glwagner** [comment]
I would also experiment with the 'molecular' diffusivity/viscosities. What happens when they are all set to the same number? Some mixing up of the constants could cause a bug.

Changing the reference density might be a good sanity check. It drops out of the incompressible Navier-Stokes equations so it's value shouldn't change results (ie it could be 1 or it could be κh)...

**Comment by ali-ramadhan** [comment]
Closing this as we have decided to go with the verification experiments outlined in https://github.com/climate-machine/Oceananigans.jl/issues/346.
