### ISSUE TITLE
Physics tests for doubly-periodic domains with analytic solutions

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#157]
At some point we should implement the following tests suggested by @edoddridge in https://github.com/climate-machine/Oceananigans.jl/issues/81.

- [ ] Spin down of a flow-field under the influence of friction
- [ ] Thermal wind balance: specify a density structure and compare model velocity fields with analytical solution
- [ ] Rayleigh–Bénard convection (I think analytic solutions exist at low Rayleigh number?)
- [ ] Onset of baroclinic instability: compare growth rates with analytical predictions

**Comment by miguelraz** [comment]
Hello @ali-ramadhan and Team Oceananigans!
I am a 6th semester physics student at UNAM, Mexico and I am thinking of taking on some of these for an end of semester project for a course I am taking in continuous media physics.
I have experience in developing packages in Julia, and am familiar with numerical methods.
What would be the first steps to take in order to formalize the problems to be analytically solved and computationaly verified?
I understand if it isn't feasible. Thanks!

**Comment by ali-ramadhan** [comment]
Hi @miguelraz, that's awesome! Thanks for taking the time to read through the issues and for posting. If you have some time we can talk over text (e.g. Slack) or voice (e.g. Hangouts or Skype) to figure out some possibilities if you're interested?

Unfortunately I'm on the road for a while so probably can't talk until May 13-15 or after May 21 but let me know!

I think we're still figuring out the tests. Some of these aren't really well-developed. For example, @mukund-gupta did some work on the thermal wind balance test (work in progress, see pull request #179) but it turns out it's not super easy to implement properly since we're solving the rotating incompressible Navier-Stokes equations with the Boussinesq approximation.

That said, I'm sure we can figure out some cool examples! What sort of stuff are you interested in?

**Comment by glwagner** [comment]
@miguelraz my two cents are that I think this is certainly feasible.

I think the first step is to write up some kind of document (can you use latex?) that outlines the problem(s) you would like to solve. This is the biggest barrier. The spin-down problem is probably the simplest. I think thermal wind should also be possible, but I would use a simpler profile than in #179 with sines and cosines rather than Gaussians. 

Another fun problem would be the propagation of an internal wave (or some shape), which is simpler than baroclinic instability (which requires you to solve an eigenvalue problem for some assumed initial condition --- because our domain is periodic, this may be slightly non-trivial). The most difficult problem suggested in this post is probably the saturated Rayleigh-Benard solutions.

Once the problems and their solutions are written out and well-defined, it should not be too difficult to implement them in Oceananigans (especially if we lend a helping hand).

I'm happy to help with the internal wave example.

**Comment by johncmarshall54** [comment]
Miguel, agree with Greg that a latex document would be good.  How about an Ekman spiral? Take the 'winds blowing over the ocean' example (see video) and blow a steady wind over a resting ocean of constant density. We need to fix a bug that crept in in Coriolis, but that can be easily done. You would test the model against the analytical solution. John

**Comment by miguelraz** [comment]
@ali-ramadhan, @glwagner , @johncmarshall54 : Thank you all for your very kind responses!
1. I have no problem writing a latex document.
2. If I could tackle all these problems, that would be quite cool, but as I am about to enter into finals I think I should focus on the "spin-down" problem as a start and then work my way up on the rest.
3. Yes, I am on the Julia slack, and don't mind joining another.
4. I'm interested in anything with a slightly-more-complicated-than-undergrad-class-but-not-phd-level.

@glwagner I tried searching for the spin-down problem but I'm not yet too familiar with the English terms - (I study in spanish).
Would you happen to have a handy link so I can begin a draft?

**Comment by ali-ramadhan** [comment]
Hey @miguelraz I'm back online now and should be free to talk if you're still interested in running some of those simulations!

We worked on a Rayleigh-Benard example a little while ago but it probably needs updating a little bit.

I'll message you on Slack as well, might be easier than talking through this issue.

**Comment by ali-ramadhan** [comment]
Closing this as we have decided to go with the verification experiments outlined in https://github.com/climate-machine/Oceananigans.jl/issues/346.
