### ISSUE TITLE
Tidal sloshing forcing function

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#212]
Wonder what the forcing function for this might look like.

**Comment by glwagner** [comment]
We can't specify this at the moment because the forcing function does not take the currently model time `t` as an argument.

I'm not sure whether you mean a barotropic tide or an internal tide. For a barotropic tide it would simply be something like  `U/σ * sin(σ*t)`, where `U` is the tidal velocity and `σ` is the tidal frequency.

A barotropic tide is not very interesting in the model right now because the bottom is flat. So it would have no effect on the solution.

For an internal tide you are actually forcing an internal wave, so you design a forcing so that it excites a motion that satisfies the internal wave dispersion relation. This is potentially interesting because an internal tide induces strains that can modulate the intensity of small-scale turbulence.

**Comment by ali-ramadhan** [comment]
Thanks for the suggestions @glwagner!

Closing this issue as it isn't relevant to Oceananigans. Once/if we decide to start modeling the effects of tides it should go in this repository: https://github.com/ali-ramadhan/europa-hydrothermal-plumes
