### ISSUE TITLE
β-plane and full Coriolis

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#28]
For long Cartesian slices? Will this work on a Cartesian grid? I know a full treatment of Coriolis in the ocean is nontrivial...

**Comment by glwagner** [comment]
You cannot implement any kind of variable Coriolis force with horizontally periodic boundary conditions, because the equations are no longer periodic in that case.

You *can* use a Cartesian grid with an arbitrarily variable Coriolis force if you implement non-periodic boundary conditions in the north-south direction.

**Comment by ali-ramadhan** [comment]
Good point, you're right of course. I guess for the model's current purpose then this is a non-issue then.

**Comment by ali-ramadhan** [comment]
Reopening as we're working towards having a channel model #100 where we'll want to be on a β-plane.

**Comment by ali-ramadhan** [comment]
Closing as this has been resolved as part of PR #438.
