### ISSUE TITLE
Recommended CFL?

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#353]
For the "model setup" section of the documentation where we'll describe how to use the `TimeStepWizard` to choose adaptive time steps, I was thinking it would be good to recommend some CFL values.

I think with 2nd-order Adams Bashforth we're limited to CFL < 0.5, so I'm thinking of recommending to start with CFL = 0.3 then decrease if issues are encountered. I usually run with 0.15 < CFL < 0.3.

@glwagner What do you usually run with?

@jm-c @christophernhill Any wisdom from MITgcm?

**Comment by glwagner** [comment]
@ali-ramadhan I typically use 0.2. Smaller values are needed for spin-up.

However, for a verification experiment I am currently attempting, it seems that even 0.1 is too large... ?

(We should implement an RK3 time stepper....)

**Comment by ali-ramadhan** [comment]
I see. Good to mention the spin up. Yeah for the stratified Couette flow I've been using 0.1 as well..

RK3 would be awesome.

**Comment by glwagner** [comment]
In some simulations I am doing to reproduce the experiment of [Kato and Phillips (1969)](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/on-the-penetration-of-a-turbulent-layer-into-stratified-fluid/1D763D80170943E6FFA0573DFE20F091), I find that I need CFL=0.1 for accurate results. The experiment was done with salt, so that the tracer molecular diffusivity is low (1.2e-9), and the simulation has a relatively low Reynolds number. I'm not sure if that is the reason for needing a relatively low CFL.
