### ISSUE TITLE
Recommendations for seeding noise in initial conditions

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#354]
For the "model setup" section of the documentation might also be good to give some suggestions on how to add noise to initial conditions if needed.

For example, mentioning that noise needs to be added to every field if running with the AMD closure.

But I've also been burned by adding noise throughout the domain (for DNS) so maybe also mention to only add noise where it's needed (e.g. only at the surface or bottom grid point). Or for AMD, noise can be damped with an exponential.

For some reason I've been using `1e-4` as the standard deviation for my noise but this seems really high so I'm starting to use `1e-10 ~ 1e-8` now.

**Comment by glwagner** [comment]
Apart from AMD, the principle purpose of noise is to encourage a transition to turbulence, I think. For that purpose the amplitude of the noise is a subjective modeling / science decision and I'm not sure we can or should give recommendations.

As for the fact that a divergent velocity field can cause problems... this is really a fluid dynamics point, rather than a point that's specific to any numerical model, right? Should we comment on such matters? I'm not averse to the idea, but think it should be eyed askew as its a bit of a black hole...

But I agree that documentation on AMD should include the fact that fields cannot be constant.

**Comment by glwagner** [comment]
@ali-ramadhan, I think with #383 the issue of seeding with noise is now primarily a science question, eg, do you need to facilitate a transition to turbulence from an unstable initial state? As such, I think we can relegate these comments to a "science advice" section in the docs (if we are willing to take a stance on such issues, which is perhaps not completely out of scope).

**Comment by ali-ramadhan** [comment]
Nice, yeah I agree it's now more "modeling advice".

I think it might be very useful to have a "Tips and tricks" section with general advice on diagnosing why your model blows up, how to determine which resolution is "enough", how to tell if you're resolving the dynamic of interest, when/how to use sponge layers, seeding initial conditions with noise, etc.
