### ISSUE TITLE
Better Value and Gradient boundary condition implementation

### ISSUE THREAD

**Issue by glwagner** [climate-machine/Oceananigans.jl#371]
Idea: 

* continue to use `calculate_boundary_source_terms` to add fluxes specified via `Flux` boundary conditions (and also via potential new future boundary condition types), *but*
* use halo filling + interior source term calculation, rather than `calculate_boundary_source_terms`, to enforce `Value` and `Gradient` boundary conditions

Advantages:

* this change eliminates the need for diffusivities to be known by `calculate_boundary_source_terms` --- diffusivities are only needed if enforcing `Flux` boundary conditions via halos, or to enforce `Value`/`Gradient` boundary conditions via `calculate_boundary_source_terms`; both of these situations are avoided with this change;
* nonlinear diffusivities that depend on gradients at the boundary can be calculated correctly for `Value` and `Gradient` boundary conditions
* gradient information is now included in output for `Value` and `Gradient` boundary conditions and can be used in post-processing
* the `calculate_boundary_source_terms` function remains a part of the algorithm for `Flux` boundary conditions, or more complicated boundary conditions (like those associated with irregular bathymetry).

Previously, we were operating under the assumption that we should either fill halos for all inhomogeneous boundary condition types, or use `calculate_boundary_source_terms`. For some reason, we did not consider that our method of enforcing inhomogeneous boundary conditions could (and perhaps should) depend on the *type* of the boundary condition. 

Thoughts?

**Comment by johncmarshall54** [comment]
I am in favor of this change but I think Jeanmichel might not be. J-M?

**Comment by christophernhill** [comment]
@glwagner and @ali-ramadhan I took a quick look. 
I think you should go ahead and merge, but quick comments for future reference - 

1. there are a bunch of changes unrelated to the PR in the PR. They are probably there by accident, but the Git gods really don't like that. When done well a PR can be a very helpful record for show what needs to be changed to achieve "X". When the PR is polluted with random other stuff that valuable use is lost. Most git projects more diligent about avoiding polluted PRs, which can be useful. 

2. I think ultimately we want halos to just be a thing that does a slightly more general form of what is in ::PBC mode. Everything else is not in halo rules. This is where we ended up in MITgcm and is similar to what is in MPIStateArray in the DG work (I am fairly sure!). A distinction to maybe think about is a set of halo() functions that just do the stuff that does not appear in any of the equations. Anything in equations turns out to be stuff that people may want to tinker with in surprisingly interesting ways. For example someone ultimately might want to do a numerical experiment that has flux BC on some set of the one bit of a boundary, something else on another bit etc.... (people do do things like this). For better or worse having bc's better separated from halos may ultimately prove the right thing. For now I wouldn't worry about it though! 

3. Related to 2. I suspect that trying to express complicated things like hybrid bc's will eventually break  reducing bc to a type. Types are good for simple things, but Type::ItsComplicated is often also needed eventually.

**Comment by ali-ramadhan** [comment]
@glwagner is this resolved now that PR #389 has been merged?

**Comment by glwagner** [comment]
Quite so.
