### ISSUE TITLE
Diagnostic for computing horizontal averages of fluxes

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#428]
We need a diagnostic to compute the horizontal average of terms like `K * dT/dz` which can't be done with the existing `HorizontalAverage` diagnostic.

I have an implementation that needs to be polished up, and may take a bit of thought if we want to integrate it with the existing diagnostics:
https://github.com/ali-ramadhan/seasonal-cycle-mixed-layers/blob/6e9834000561bdbbbcb9812e87f8dbdd876e48b0/simulation/deepening_mixed_layer.jl

**Comment by glwagner** [comment]
I am planning to implement a diagnostics specification system (abstraction for defining kernels in terms of operations on fields) which will address this issue.

**Comment by ali-ramadhan** [comment]
Nice!

Seems like you've already implemented some useful stuff here:
https://github.com/glwagner/ColumnModelOptimizationProject/blob/master/les/utils.jl
https://github.com/glwagner/ColumnModelOptimizationProject/blob/master/les/kernels.jl

**Comment by glwagner** [comment]
True, but the abstraction I was thinking about would be far more general! Users would define fluxes by writing code of the form

```julia
average_flux = HorizontalAverage(κₑ * ∂z(T), frequency=10)
```

for example, where `κₑ` and `T` are eddy diffusivity and temperature fields. The operator `∂z(T)` will return an object `Derivative` and the operation `κₑ * ∂z(T)` will return a `BinaryOperation`. These objects will behave like fields in the sense that calling `getindex(obj, inds...)` will perform the necessary interpolation, difference, and arithmetic operations to calculate the values at the specified indices. In particular, running such `HorizontalAverage` diagnostic will compute the flux with a kernel (eg `compute!(scratch_array, binary_operation)`) and store it in some intermediate scratch array (like pressure), and then compute the horizontal average of that.

Still not sure how to specify momentum fluxes, since those expressions are a bit more complicated. But we can provided aliases for those cases that utilize this abstraction system.

**Comment by ali-ramadhan** [comment]
Awesome! Still need to take a look at PR #463.

> Still not sure how to specify momentum fluxes, since those expressions are a bit more complicated. But we can provided aliases for those cases that utilize this abstraction system.

Yeah might make sense to define convinient aliases for these complicated expressions. The "available diagnostics" lists from MITgcm, ECCO, or SOSE might give an idea for what diagnostics people usually ask for.

With #463 it seems like we'll be able to provide all existing diagnostics (+ infinitely many more) just be defining one-liner abstract operations.

**Comment by glwagner** [comment]
> With #463 it seems like we'll be able to provide all existing diagnostics (+ infinitely many more) just be defining one-liner abstract operations.

Yes, that is the goal. Convenient aliases make sense to me; with the abstraction they will hopefully be easy to maintain.
