### ISSUE TITLE
Each tracer should have its own diffusivity

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#430]
Not an immediate concern and but right now the diffusivity `κ` is shared between temperature and salinity whereas they should be different.

Perhaps this should be worked on at the same time as arbitrary tracer fields (#25).

**Comment by glwagner** [comment]
I agree that this is naturally addressed when arbitrary tracer fields are implemented. 

Note that this applies not just to diffusivities (if you're referring to `ConstantIsotropicDiffusivity`), but to background diffusivities associated with LES closures, and also to the turbulent prandtl numbers associated with the Smagorinsky closures.

**Comment by glwagner** [comment]
My plan:

* When the user specifies a single diffusivity, this diffusivity is applied to all tracer fields
* Otherwise, diffusivities are specified by a named tuple, where names correspond to diffusivity names, eg

```julia
tracers = (:T, :S)

closure = ConstantIsotropicDiffusivity(ν=1e-6, κ=(T=1e-6, S=1e-7))
```

and

```julia
tracers = (:T, :S)

closure = ConstantIsotropicDiffusivity(ν=1e-6, κ=1e-6, tracers=tracers)
```

would be possible use patterns. The `tracers` keyword is only required when the diffusivity is not itself a named tuple.

Or, possibly we can require that `tracers` is supplied, eg

```julia
closure = ConstantIsotropicDiffusivity(tracers, ν=1e-6, κ=(T=1e-6, S=1e-7))
```

This last pattern would be useful if, for example, we want to do input validation on the diffusivity tuple.

We may also want to think about designs / syntactic sugar for making the handling of large numbers of passive tracers easier.

**Comment by ali-ramadhan** [comment]
Awesome! Yeah just reviewed PR #452 which looks great. I just opened the issue to keep track of things, but the arbitrary tracers thing got resolved pretty quickly.
