### ISSUE TITLE
First example (hot bubble) fails when defining the model

### ISSUE THREAD

**Issue by tomchor** [climate-machine/Oceananigans.jl#449]
I may be missing something, but in the first example of the documentation I get an error when creating the model. The prior example (the still ocean without anything) runs fine.

Based on the docs I think at some point you changed the keyword from `arch` to `architecture` in the `Model` function and didn't change the documentation, but since I'm not familiar with Oceananigans I decided to post here instead of making a pull request.

Cheers

Also, quick edit: the link to `rising_thermal_bubble_2d.jl` in the front page is broken.

**Comment by ali-ramadhan** [comment]
Hey @tomchor thank you for testing out the example and reporting this! Indeed we did a lot of refactoring for v0.11 and you've become the first victim haha.

I updated the example with the right keyword argument and removed the stale link (PR #450). 

I'd like to revive the full rising thermal bubble example soon but for now @glwagner has put together some pretty cool examples with plots: https://github.com/climate-machine/Oceananigans.jl/tree/master/examples

Let us know if you had a simulation in mind you're trying to run, we're more than happy to help!

**Comment by tomchor** [comment]
Thanks! I'll take a look. My end goal here is to recreate the set-up in [this paper](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/frontogenesis-and-frontal-arrest-of-a-dense-filament-in-the-oceanic-surface-boundary-layer/2FFBE4503C590CE7BDB1B8BAA236C387) and see if I can see some submesoscale activity. This is just a proof (or disproof I guess) of concept, so I'm aiming for a coarser resolution and other simplifications. Any tips are greatly appreciated.

On a side note, since you asked, I _am_ going through some difficulties running the same example with a GPU. My inexperience with GPUs is keeping me from figuring this one out. Should I create another issue? (I'm not sure how much you guys want to be involved in these debugging processes...)

Thanks!

**Comment by ali-ramadhan** [comment]
> On a side note, since you asked, I am going through some difficulties running the same example with a GPU. My inexperience with GPUs is keeping me from figuring this one out.

What GPU are you running on? You'll need an Nvidia GPU and the CUDA library installed. Installing Oceananigans through the Julia package manager should install all the required Julia package dependencies (but won't install CUDA itself).

Are you getting any errors?

Hmmm, so there is a small caveat that `Nx` and `Ny` need to be multiples of 16 on the GPU right now, although you'd get an error about this.

> Should I create another issue?

Hmmm yeah that might be a good idea just to keep each issue self-contained.

> (I'm not sure how much you guys want to be involved in these debugging processes...)

We're very interested in being involved with the debugging process! We're still in early development so I'd expect things to break quite often, and we still haven't ironed out all the bugs and usability issues.

We've also mostly been using the model ourselves (hard to improve usability if you know all the internals haha), so if you're willing to report issues it would be a huge help with development!

**Comment by ali-ramadhan** [comment]
> My end goal here is to recreate the set-up in [this paper](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/frontogenesis-and-frontal-arrest-of-a-dense-filament-in-the-oceanic-surface-boundary-layer/2FFBE4503C590CE7BDB1B8BAA236C387) and see if I can see some submesoscale activity. This is just a proof (or disproof I guess) of concept, so I'm aiming for a coarser resolution and other simplifications. Any tips are greatly appreciated.

If you're mostly interested in the oceanic boundary layer and don't need topography or a free surface, then Oceananigans probably has most of what you need. (See #443 if you're interested in surface physics.)

8192×3072×256 ~ 10¹⁰ grid points is out of our reach for the moment although our plan is to be able to run these super large simulations one day!

We're still limited to 1 GPU (with 16 or 32GB RAM) which lets us go up to ~5×10⁷ grid point. We could probably extend that to ~10⁸ grid points if we implement #98 but even then it would take 50-100 GPUs to reach 10¹⁰ grid points.

We've mostly been running oceanic mixed layer simulations with a focus on vertical mixing so no need for a ton of horizontal resolution, but we do have horizontal mixing problems in mind at which point we'll need to start running on multiple GPUs with MPI. This is something we're starting to get serious about as we do need it ourselves.

Not sure how coarse you can go but if you can go down to ~10⁸ grid points then maybe Oceananigans can be useful. If the factor of ~2 reduction in memory usage from #98 would be useful for you, let us know and we can look into implementing it. In general, I think we're happy to work together on features that you might need.

Out of curiosity, what LES model are you currently using?

**Comment by glwagner** [comment]
@tomchor just wanted to echo @ali-ramadhan's thank you for finding that bug!

Right now Oceananigans shines for medium-size LES problems around 256^3, perhaps up to 384^3. For that application I think you may find it is as fast or faster than other codes. On that note, it'd be great to compare performance with other codes for this problem size. 

For utterly massive problems like the one reported in the Sullivan paper you've posted, Oceananigans is probably not the right tool right now. We haven't experimented with multi-node parallelism yet, but as @ali-ramadhan suggests, its possible we will start working on either multi-CPU parallelism or multi-GPU parallelism soon. For reproducing the Sullivan paper, you may want multi-CPU parallelism simply because of the sheer number of nodes you'll need.

It's worth noting that our AMD turbulence closure *may* be less resolution-dependent than the TKE-based closure used by NCAR LES / Sullivan (and yourself?) and thus it may be possible to run at lower resolution (potentially saving factors of 10-100 in resolution. A [paper by Abkar and Moin (2017)](https://link.springer.com/article/10.1007/s10546-017-0288-4) hints at the potential for very coarse simulations with AMD.

**Comment by glwagner** [comment]
@tomchor should have also echoed @ali-ramadhan that we are very happy to help with debugging and all manner of questions.

**Comment by tomchor** [comment]
@ali-ramadhan I'm running on my desktop's GPU just to get a sense of the performance increase at the moment. According to `nvidia-smi` my card is a `NVS 310` (I apologize if I didn't get that right, I really have zero experience with GPUs). I'll create another issue to report this properly. Thanks for the feedback, though!

And I'm running our own group's LES model. Unfortunately I'm not allowed to share the code, but you can read about it [here](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2018GL080296).

@glwagner I'd be very willing to compare performances of our LES with Oceananigans. The caveats here being that
- our model of choice ([lagrangian-averaged scale-dynamic](https://aip.scitation.org/doi/10.1063/1.1839152)) takes relatively long to calculate compared to other models, but generally needs lower resolution to achieve the same results (so in this sense it might be similar to AMD) and that
- I'm not sure how relevant it would be to compare with us, being that I'm not allowed to share the source code

If you're still interested to make a comparison just let me know! I'd be happy to help.

@ali-ramadhan @glwagner I'm not expecting at all to run their simulation at the resolution that they're running. My intent was to set-up the same case (but very coarse) and see how much I could increase the resolution (and how much activity I could see) until it became too slow or until I ran out of memory. This is basically a fun side-project, and not an actual research attempt if I'm being honest :)

Thank you both for the helpful responses! I'm glad to help with whatever bugs or attempts at simulations that I can!

**Comment by glwagner** [comment]
@tomchor when I get the chance, I will open another issue about performance comparisons and tag you. Right now for 256^3 we are around 0.03--0.05 s per time-step with two tracers and the AMD closure. This means that an 8 day simulation with 5 s time-steps will run in a few hours of wall time. Since we haven't attempted much of any performance optimization, we hope that performance will improve further in the future. It's unclear what will happen for multi-CPU and multi-GPU architectures, however.

Interesting that you're using a Lagrangian-averaged dynamic closure. I'd like to see how that compares to AMD. It's possible we could implement a Lagrangian-averaged dynamic closure, but probably not in the near term since I think we'd want to have particle advection features first.

**Comment by tomchor** [comment]
@glwagner Yes, I'd like to make those comparisons too. Not only because of efficiency but also to compare results. We generally ignore this, but I think the SGS model can actually impact the results significantly. The atmosphere people have done some comparison studies on this issue but I don't think that has been done in the ocean. It would be nice to have a paper comparing turbulence statistics for LASD, AMD and NCAR's TKE closure!

**Comment by glwagner** [comment]
@tomchor I agree wholeheartedly, both performance and model accuracy are interesting. I focused on performance because I suspect that because `Oceananigans` uses the GPU, it may be substantially faster than existing CPU-based codes. Also, I feel performance optimization can be a bit tricky, and in some cases is limited more by technology / hardware / programming language than software --- thus its important to know where `Oceananigans` stands now so we know how much effort we need to invest there. Implementing a new LES model or upgrading model numerics is, on other hand, typically easier and mostly a case of upgrading high-level software, I think --- especially in a high-level language like julia. We may also have abstractions soon that make implementing new LES models / equations much easier. (Verifying the accuracy of the LES model is another story...)

It could be interesting to set up a model intercomparison project like you suggest, similar to what's been done in the atmosphere. We could pick a few physical scenarios for the comparison --- perhaps a reproduction of observations in a place that we think LES might be successful, and perhaps some idealized experiment(s), maybe involving submesoscales or reactive tracers or a combination of the two. Are you interested in helping set something like that up? 

We have a nice opportunity at the upcoming Ocean Sciences to coordinate such a project --- people will be there who have deep familiarity with most of the ocean LES codes that I'm aware of (all 7 of them...). In fact, they are all presenting in the boundary layer turbulence session that we are both presenting in!

**Comment by tomchor** [comment]
@glwagner Yes, I'm definitely interested! I'm still not 100% sure I'll be able to go to Ocean Sciences (due to lack of funding, unfortunately), but I'll probably be able to at least spend one day there given that it's so close. And I agree that that'd be the perfect opportunity to coordinate something like this!
