### ISSUE TITLE
Specifying the vertical spacing with a function may not work in the halo regions.

### ISSUE THREAD

**Issue by ali-ramadhan** [climate-machine/Oceananigans.jl#531]
For example, you need values of `ΔzC[0]` and `ΔzF[0]` (in the halo regions) to compute vertical derivatives at the top and bottom. I think the halo cells in this case are all the same size and equal in size to the top-most or bottom-most cells.

The simplest way to get this to work is to provide `ΔzC` and `ΔzF` as offset arrays and we won't have to do anything special at the boundaries.

Hmmm, on a domain `z ∈ [0, L]` I guess a hack would be to call e.g. `ΔzC(x, y, min(max(0, z), L))` instead of `ΔzC(x, y, z)` but this seems dirty.

I don't see a disadvantage of using an offset array over a function in this case. Users can specify `ΔzC` using an array or a function which we convert to an offset array.

This issue also crops up in the atmosphere where you need to take derivatives of a base state, but if it's defined as a function then you run into this issue at the boundaries.

**Comment by glwagner** [comment]
I’m fine with using arrays. However, we probably don’t want to write code that assumes anything about grid spacing at the boundaries. In other words, i think we should write our algorithm so that the spacing of halo cells is accessed explicitly, rather than assumes to be equal to the spacing of cells just inside the boundary.
